server:
  port: 8080

spring:
  h2:
    # 기본 JDBC URL: jdbc:h2:~/test
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:crud
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

  # OAuth2
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: {your-okta-client-id}
            client-secret: {your-okta-client-secret}
            scope: openid, email, profile
        provider:
          okta:
            # 응답 확인 -> https://{your-okta-domain}/oauth2/default/.well-known/openid-configuration
            issuer-uri: https://{your-okta-domain}/oauth2/default

logging:
  level:
    org.hibernate.type: trace

# API Docs
springdoc:
  api-docs:
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC